apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: duniv-pvc
  namespace: nimesh-ns
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "5Gi"
  storageClassName: storageC