apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: raj-pod-access
  namespace: nimesh-ns
subjects:
- kind: User
  name: raj
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io