apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.backend.name }}
  namespace: nimesh-ns
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: mysql
  serviceName: "mariadb"
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mysql
    spec:
      # tolerations:
      # - key: "env"
      #   operator: "Equal"
      #   value: "dev"
      #   effect: "NoExecute"
      # affinity:
      #   # podAffinity:
      #   #   requiredDuringSchedulingIgnoredDuringExecution:
      #   #   - labelSelector:
      #   #       matchExpressions:
      #   #       - key: app
      #   #         operator: In
      #   #         values:
      #   #           - duniv
      #   #     topologyKey: "kubernetes.io/hostname"
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector:
      #         matchExpressions:
      #         - key: app
      #           operator: In
      #           values:
      #             - duniv
      #       topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql-cont
        image: {{ .Values.backend_image.repository }}:{{ .Values.backend_image.tag }}
        ports:
        - containerPort: {{ .Values.backend.ports.containerPort}}
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: duniv-secret
                key: MYSQL_ROOT_PASSWORD
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: duniv-secret
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: duniv-secret
                key: DB_PASSWORD
        volumeMounts:
          - name: mysql-vct
            mountPath: /var/lib/mysql
          - name: mysql-q
            mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-q
        configMap:
          name: mysql-init
  volumeClaimTemplates:
    - metadata:
        name: mysql-vct
      spec:
        accessModes: ["ReadWriteMany"]
        storageClassName: storaged
        resources:
          requests:
            storage: "2Gi"
        
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend_service.name}}
  namespace: nimesh-ns
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
  clusterIP: None